# Form implementation generated from reading ui file 'dialogWin.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(293, 391)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(20, 20, 261, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(20, 150, 251, 192))
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 130, 241, 16))
        self.label.setObjectName("label")
        self.Button_Listed = QtWidgets.QPushButton(Dialog)
        self.Button_Listed.setGeometry(QtCore.QRect(110, 350, 81, 21))
        self.Button_Listed.setObjectName("Button_Listed")
        self.Button_New = QtWidgets.QPushButton(Dialog)
        self.Button_New.setGeometry(QtCore.QRect(20, 110, 51, 21))
        self.Button_New.setObjectName("Button_New")
        self.Button_deselect = QtWidgets.QPushButton(Dialog)
        self.Button_deselect.setGeometry(QtCore.QRect(20, 350, 81, 21))
        self.Button_deselect.setObjectName("Button_deselect")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 261, 31))
        self.label_2.setObjectName("label_2")
        self.Button_Extra = QtWidgets.QPushButton(Dialog)
        self.Button_Extra.setGeometry(QtCore.QRect(80, 110, 51, 21))
        self.Button_Extra.setObjectName("Button_Extra")
        self.Button_Abort = QtWidgets.QPushButton(Dialog)
        self.Button_Abort.setGeometry(QtCore.QRect(199, 350, 71, 21))
        self.Button_Abort.setObjectName("Button_Abort")
        self.label_Title = QtWidgets.QLabel(Dialog)
        self.label_Title.setGeometry(QtCore.QRect(20, 50, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_Title.setFont(font)
        self.label_Title.setObjectName("label_Title")
        self.VOcheckBox = QtWidgets.QCheckBox(Dialog)
        self.VOcheckBox.setGeometry(QtCore.QRect(140, 110, 131, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VOcheckBox.sizePolicy().hasHeightForWidth())
        self.VOcheckBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        self.VOcheckBox.setFont(font)
        self.VOcheckBox.setObjectName("VOcheckBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit, self.listWidget)
        Dialog.setTabOrder(self.listWidget, self.Button_deselect)
        Dialog.setTabOrder(self.Button_deselect, self.Button_Listed)
        Dialog.setTabOrder(self.Button_Listed, self.Button_New)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Is this new?"))
        self.label.setText(_translate("Dialog", "Not new? please select from list:"))
        self.Button_Listed.setText(_translate("Dialog", "As Listed"))
        self.Button_New.setText(_translate("Dialog", "New"))
        self.Button_deselect.setText(_translate("Dialog", "Deselect"))
        self.label_2.setText(_translate("Dialog", "TextLabel"))
        self.Button_Extra.setText(_translate("Dialog", "Extra"))
        self.Button_Abort.setText(_translate("Dialog", "Abort"))
        self.label_Title.setText(_translate("Dialog", "TextLabel"))
        self.VOcheckBox.setText(_translate("Dialog", " V.O. / Video / Not in Scene"))
